# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_dog_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
