# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_dog_age_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], max_length=1),
        ),
    ]
