# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-08 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20190207_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(default='u', max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='u', max_length=255),
        ),
    ]
