# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20190207_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(default='b', max_length=255),
        ),
    ]
