# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-21 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0008_auto_20190208_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='u', max_length=255),
        ),
    ]
