# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-02-21 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0009_auto_20190220_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_classification',
            field=models.CharField(default='u', max_length=255),
        ),
    ]
